# Generated by Django 4.0 on 2022-04-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=30)),
                ('sales_no', models.CharField(max_length=30)),
                ('bill_date', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=30)),
                ('advance', models.CharField(max_length=30)),
                ('vehicle_model_no', models.CharField(max_length=30)),
                ('vehicle_name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('net_amount', models.CharField(max_length=30)),
                ('payment_mode', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_bill',
            },
        ),
        migrations.CreateModel(
            name='tbl_book_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingID', models.CharField(max_length=10)),
                ('customerID', models.CharField(max_length=10)),
                ('serviceID', models.CharField(max_length=10)),
                ('serviceName', models.CharField(max_length=10)),
                ('serviceDate', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tbl_book_service',
            },
        ),
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model_number', models.CharField(max_length=30)),
                ('customer_id', models.CharField(max_length=30)),
                ('booking_id', models.CharField(max_length=30)),
                ('booking_date', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_booking',
            },
        ),
        migrations.CreateModel(
            name='tbl_complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintID', models.CharField(max_length=30)),
                ('customerID', models.CharField(max_length=40)),
                ('complaint', models.CharField(max_length=30)),
                ('complaintDate', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_complaints',
            },
        ),
        migrations.CreateModel(
            name='tbl_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customerid', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tbl_customer',
            },
        ),
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('hint', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_login',
            },
        ),
        migrations.CreateModel(
            name='tbl_reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewID', models.CharField(max_length=30)),
                ('customerID', models.CharField(max_length=40)),
                ('review', models.CharField(max_length=30)),
                ('reviewdate', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_reviews',
            },
        ),
        migrations.CreateModel(
            name='tbl_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_no', models.CharField(max_length=30)),
                ('customerID', models.CharField(max_length=30)),
                ('vehicle_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceID', models.CharField(max_length=30)),
                ('servicename', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tbl_service',
            },
        ),
        migrations.CreateModel(
            name='tbl_spare_parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sparepartnumber', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=40)),
                ('unit', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=40)),
                ('stockquantity', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffID', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=10)),
                ('category', models.CharField(default='Nil', max_length=15)),
            ],
            options={
                'db_table': 'tbl_staff',
            },
        ),
        migrations.CreateModel(
            name='tbl_vehicle_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('engine_capacity', models.CharField(max_length=10)),
                ('photo', models.CharField(max_length=100)),
                ('cc', models.CharField(max_length=10)),
                ('tank_capacity', models.CharField(max_length=10)),
                ('mileage', models.CharField(max_length=10)),
                ('colour', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
