# Generated by Django 4.0.1 on 2022-01-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintid', models.CharField(max_length=30)),
                ('customerName', models.CharField(max_length=40)),
                ('complaint', models.CharField(max_length=30)),
                ('complaintDate', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_complaints',
            },
        ),
        migrations.CreateModel(
            name='tbl_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customerid', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_customer',
            },
        ),
        migrations.CreateModel(
            name='tbl_reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewid', models.CharField(max_length=30)),
                ('customerName', models.CharField(max_length=40)),
                ('review', models.CharField(max_length=30)),
                ('reviewdate', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_reviews',
            },
        ),
        migrations.CreateModel(
            name='tbl_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceid', models.CharField(max_length=30)),
                ('servicename', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tbl_service',
            },
        ),
        migrations.CreateModel(
            name='tbl_spare_parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sparepartnumber', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=40)),
                ('unit', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=40)),
                ('stockquantity', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staffid', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_staff',
            },
        ),
        migrations.CreateModel(
            name='tbl_vehicle_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model_number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('engine_capacity', models.CharField(max_length=40)),
                ('photo', models.CharField(max_length=30)),
                ('cc', models.CharField(max_length=40)),
                ('tank_capacity', models.CharField(max_length=30)),
                ('mileage', models.CharField(max_length=40)),
                ('colour', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=40)),
            ],
        ),
    ]
