# Generated by Django 4.0.2 on 2022-05-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_customer',
            name='Customerid',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tbl_customer',
            name='Password',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tbl_login',
            name='password',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tbl_login',
            name='userid',
            field=models.CharField(max_length=60),
        ),
    ]
