# Generated by Django 4.0.1 on 2022-01-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('hint', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_login',
            },
        ),
    ]
