# Generated by Django 4.0.1 on 2022-01-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app1', '0002_tbl_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_staff',
            name='category',
            field=models.CharField(default='Sales', max_length=15),
        ),
    ]
