# Generated by Django 4.0.1 on 2022-02-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_tbl_vehicle_booking_alter_tbl_vehicle_model_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_vehicle_booking',
            name='booking_id',
            field=models.CharField(default='j', max_length=30),
            preserve_default=False,
        ),
    ]
