# Generated by Django 4.0.1 on 2022-02-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_tbl_vehicle_booking_tbl_booking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_complaints',
            old_name='complaintid',
            new_name='complaintID',
        ),
        migrations.RenameField(
            model_name='tbl_complaints',
            old_name='customerName',
            new_name='customerID',
        ),
        migrations.RenameField(
            model_name='tbl_reviews',
            old_name='customerName',
            new_name='customerID',
        ),
        migrations.RenameField(
            model_name='tbl_reviews',
            old_name='reviewid',
            new_name='reviewID',
        ),
        migrations.RenameField(
            model_name='tbl_service',
            old_name='serviceid',
            new_name='serviceID',
        ),
        migrations.RenameField(
            model_name='tbl_staff',
            old_name='Staffid',
            new_name='staffID',
        ),
    ]
