# Generated by Django 4.0.1 on 2022-02-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_complaintid_tbl_complaints_complaintid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_book_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingID', models.CharField(max_length=10)),
                ('customerID', models.CharField(max_length=10)),
                ('serviceID', models.CharField(max_length=10)),
                ('serviceName', models.CharField(max_length=10)),
                ('serviceDate', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tbl_book_service',
            },
        ),
        migrations.CreateModel(
            name='tbl_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_no', models.CharField(max_length=30)),
                ('customerID', models.CharField(max_length=30)),
                ('vehicle_number', models.CharField(max_length=30)),
                ('model_no', models.CharField(max_length=30)),
            ],
        ),
    ]
