# Generated by Django 4.0.1 on 2022-02-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_tbl_book_service_tbl_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_sales',
            name='model_no',
        ),
    ]
