# Generated by Django 4.0.1 on 2022-03-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_tbl_sales_model_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=30)),
                ('sales_no', models.CharField(max_length=30)),
                ('bill_date', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=30)),
                ('advance', models.CharField(max_length=30)),
                ('vehicle_model_no', models.CharField(max_length=30)),
                ('vehicle_name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('net_amount', models.CharField(max_length=30)),
                ('payment_mode', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_bill',
            },
        ),
        migrations.AlterField(
            model_name='tbl_customer',
            name='Address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tbl_customer',
            name='Customerid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_customer',
            name='Email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_customer',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_customer',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_staff',
            name='Email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_staff',
            name='Name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_staff',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_staff',
            name='Status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_staff',
            name='staffID',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_vehicle_model',
            name='cc',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_vehicle_model',
            name='colour',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tbl_vehicle_model',
            name='engine_capacity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_vehicle_model',
            name='mileage',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_vehicle_model',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_vehicle_model',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_vehicle_model',
            name='tank_capacity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_vehicle_model',
            name='vehicle_model_number',
            field=models.CharField(max_length=10),
        ),
    ]
